

import { FlowTemplate, FlowNode, FlowEdge } from "@/types/flowTypes";
//import { nodePositions } from "../lib/nodePositions";
import { tenantId, transformData, ieltsReadingWelcomeMessage, startNodePositions, positionConstants } from "@/lib/constants";
import { createEdgeNode } from "../lib/FlowEdge/edge";
import { createMessageNode, createButtonNode } from "../lib/FlowNode/node";
import { createStartButtonNodeAtPosition, createFixedMessageNodeAtPosition, createEndButtonNodeAtPosition } from "@/lib/FlowNode/createDataNodes";
import { createQuizNodesAtStartIndex } from "@/lib/Ielts/createQuizNodes";
import { IELTSQuizType } from "@/types/quiz";
import { FlowNodePosition } from "@/types/flowTypes";

const questText = "From the list of words pick out the correct one";
let nodeIndex = 0;
let nodePositions = startNodePositions;

const extractQuestions = (data: string): IELTSQuizType[] => {
	const questions: IELTSQuizType[] = [];
	const lines = data.trim().split("\n\n");
	const keys = ["A", "B", "C", "D", "E", "F", "G"];

	lines.forEach(line => {
		let question = `<p>${questText}</p></br>`;
		const options: Record<string, string> = {};
		let correctOption = "";

		const optionsArray = line.trim().split("\n");

		optionsArray.map((option, index) => {
			// Match pattern like "1a. SPDE" or "2b.BUZY"
			const match = option.match(/^(\d+)([a-c])\.?\s*(.+?)(\s*✅)?$/);
			if (match) {
				const optionText = match[3].trim();
				options[keys[index]] = optionText;
				question += `<p>${keys[index]}) ${optionText}</p>`;
				const isCorrect = match[4] ? match[4].trim() === "✅" : false;
				if (isCorrect)
					correctOption = keys[index];
			}
		})
		questions.push({ question, options, correctOption });
	});
	return questions;
}

const calculateNodePositions = (currentPositions: FlowNodePosition, nodeType: string): FlowNodePosition => {
	let newPosX = parseInt(currentPositions.posX);
	let newPosY = parseInt(currentPositions.posY);

	if (nodeType === "adjacent") {
		newPosX += positionConstants.gapX;
	}

	return {
		"posX": newPosX.toString(),
		"posY": newPosY.toString()
	}
}

export const transformSourceData = (sourceData: string, outputFileame: string): FlowTemplate => {
	const flowNodes: FlowNode[] = [];
	const flowEdges: FlowEdge[] = [];
	let sourceNodes: FlowNode[] = [];
	const questions = extractQuestions(sourceData);
	console.log(questions);


	//Node 1 -Start Message
	const startMessage = createMessageNode(
		ieltsReadingWelcomeMessage,
		true,
		nodePositions
	);
	nodeIndex++;
	nodePositions = calculateNodePositions(nodePositions, "adjacent");


	//Node 2 - Start Button
	const startButton = createStartButtonNodeAtPosition(nodePositions);

	nodeIndex++;
	nodePositions = calculateNodePositions(nodePositions, "adjacent");
	sourceNodes = [startButton];//[`${startButton.id}__${(startButton?.interactiveButtonsItems && startButton.interactiveButtonsItems.length > 0) ? startButton.interactiveButtonsItems[0].id : "default"}`]

	flowEdges.push(createEdgeNode(startMessage.id, startButton.id)); //1

	let questionNodes: any[] = [];
	questions.map((question: any, index: number) => {
		let quiz = createQuizNodesAtStartIndex(flowEdges, nodeIndex, nodePositions, sourceNodes, index, question);
		nodeIndex = quiz.nodeIndex;
		nodePositions = quiz.nodePositions;
		sourceNodes = quiz.sourceNodes;
		questionNodes = questionNodes.concat(quiz.nodes);
	});

	const endButton = createEndButtonNodeAtPosition("What next ?",
		"<p> Click option 1 to go back to main menu (IELTS LIST)</p><p> Click option 2 to start next skillbyte(in reading section sequential)</p>",
		["Option 1", "Option 2"],
		nodePositions);
	nodeIndex++;

	// connect sourceNodes to End Node
	sourceNodes.map((sourceNode: FlowNode) => {
		if (sourceNode?.interactiveButtonsItems && sourceNode.interactiveButtonsItems.length > 0)
			sourceNode.interactiveButtonsItems[0].nodeResultId = endButton.id;
		flowEdges.push(createEdgeNode(
			`${sourceNode.id}__${(sourceNode?.interactiveButtonsItems && sourceNode.interactiveButtonsItems.length > 0) ? sourceNode.interactiveButtonsItems[0].id : "default"}`, endButton.id));
	});


	flowNodes.push(startMessage, startButton);
	questionNodes.map((node: any) => {
		flowNodes.push(node);
	});
	flowNodes.push(endButton);



	return {
		id: null,
		tenantId: tenantId.toString(),
		name: outputFileame,
		created: null,
		flowNodes, // generated by linking flowNodes
		flowEdges, // generated by linking flowEdges
		lastUpdated: new Date().toISOString(),
		isDeleted: false,
		transform: {
			posX: transformData.posX.toString(),
			posY: transformData.posY.toString(),
			zoom: transformData.zoom.toString()
		},
		isPro: false,
		channelTypes: ["WA"]
	};
};
